aws_region           = "us-east-1"
environment          = "dev"
vpc_cidr             = "10.10.0.0/16"
availability_zones   = ["us-east-1a", "us-east-1b"]
public_subnet_cidrs  = ["10.10.1.0/24", "10.10.2.0/24"]
private_subnet_cidrs = ["10.10.11.0/24", "10.10.12.0/24"]
single_nat_gateway   = true
cluster_version      = "1.30"
node_instance_type   = "t3.medium"
node_desired_size    = 2
node_min_size        = 1
node_max_size        = 3
rds_instance_class   = "db.t4g.micro"
rds_engine_version   = "16.4"
rds_allocated_storage = 20
rds_database_name    = "platform"
rds_master_username  = "platform_admin"
